title: Megan E Guidry # your name (or website title) here
logo: "/images/meg.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at University of Rhode Island 
  <br><br>
  Department of Biological Sciences
  <br><br>
  <a href="https://twitter.com/meg_guidry">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
